### ISSUE TITLE
Practica4_modelo_de_negocio

### ISSUE THREAD

**Issue by JeroRoque** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-de-icp-equipo-evelin#1]
[Reporte modelo de negocio.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-de-icp-equipo-evelin/files/12840958/Reporte.modelo.de.negocio.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
