### ISSUE TITLE
Práctica4

### ISSUE THREAD

**Issue by KarenGarciaGarcia** [SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-de-icp-equipo-evelin#2]
[Reporte de practica4.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-practica-de-modelo-de-negocios-de-icp-equipo-evelin/files/12861518/Reporte.de.practica4.pdf)

**Comment by josealfredo79** [comment]
Falta calificacion

**Comment by isaireyesp1** [comment]
Portada : 25
Procedimiento : 22
Figuras, ilustraciones y fotografías. : 25
Resultados y conclusiones : 22
calificación : 18.8

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
